name: Mindful Naturals
favicon: null
layout_spectrum: 0.6748520412947983
typography_spectrum: 0.790129809640348
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9655344358179718
  lightness: 0.7303985492326319
  saturation: 0.24161839648149908
  rhythmicContrast: 0.3871612867806107
purpose: []
